#!/bin/bash
# Merge multiple run results to obtain single file for each time bin 
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_1.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_1/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_2.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_2/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_3.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_3/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_4.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_4/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_5.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_5/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_6.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_6/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_7.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_7/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_8.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_8/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_9.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_9/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_10.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_10/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_11.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_11/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_12.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_12/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_13.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_13/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_14.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_14/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_15.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_15/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_16.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_16/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_17.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_17/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_18.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_18/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_19.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_19/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_20.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_20/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_21.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_21/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_22.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_22/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_23.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_23/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_24.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_24/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_25.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_25/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_26.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_26/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_27.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_27/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_28.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_28/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_29.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_29/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_30.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_30/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_31.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_31/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_32.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_32/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_33.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_33/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_34.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_34/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_35.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_35/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_36.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_36/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_37.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_37/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_38.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_38/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_39.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_39/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_40.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_40/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_41.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_41/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_42.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_42/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_43.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_43/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_44.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_44/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_45.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_45/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_49.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_49/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_50.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_50/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_51.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_51/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_52.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_52/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_53.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_53/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_54.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_54/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_55.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_55/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_56.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_56/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_57.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_57/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_58.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_58/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_59.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_59/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_60.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_60/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_61.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_61/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_62.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_62/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_63.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_63/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_64.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_64/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_65.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_65/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_66.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_66/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_67.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_67/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_68.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_68/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_69.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_69/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_70.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_70/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_71.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_71/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_72.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_72/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_73.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_73/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_74.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_74/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_75.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_75/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_76.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_76/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_77.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_77/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_78.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_78/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_79.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_79/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_80.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_80/*
hadd /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/he_flux_mc_time_81.root /afs/cern.ch/work/c/ctuysuz/private/he_flux/LSF/result_mc_time/time_81/*
