#!/bin/bash
# Create 81-3 time folders
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_1
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_2
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_3
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_4
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_5
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_6
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_7
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_8
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_9
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_10
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_11
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_12
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_13
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_14
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_15
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_16
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_17
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_18
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_19
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_20
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_21
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_22
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_23
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_24
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_25
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_26
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_27
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_28
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_29
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_30
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_31
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_32
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_33
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_34
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_35
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_36
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_37
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_38
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_39
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_40
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_41
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_42
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_43
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_44
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_45
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_49
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_50
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_51
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_52
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_53
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_54
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_55
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_56
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_57
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_58
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_59
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_60
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_61
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_62
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_63
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_64
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_65
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_66
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_67
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_68
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_69
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_70
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_71
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_72
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_73
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_74
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_75
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_76
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_77
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_78
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_79
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_80
mkdir /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_81
