#!/bin/bash
# Move root files to corresponding folders
mv he_flux_1_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_1/
mv he_flux_2_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_2/
mv he_flux_3_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_3/
mv he_flux_4_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_4/
mv he_flux_5_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_5/
mv he_flux_6_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_6/
mv he_flux_7_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_7/
mv he_flux_8_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_8/
mv he_flux_9_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_9/
mv he_flux_10_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_10/
mv he_flux_11_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_11/
mv he_flux_12_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_12/
mv he_flux_13_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_13/
mv he_flux_14_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_14/
mv he_flux_15_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_15/
mv he_flux_16_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_16/
mv he_flux_17_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_17/
mv he_flux_18_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_18/
mv he_flux_19_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_19/
mv he_flux_20_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_20/
mv he_flux_21_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_21/
mv he_flux_22_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_22/
mv he_flux_23_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_23/
mv he_flux_24_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_24/
mv he_flux_25_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_25/
mv he_flux_26_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_26/
mv he_flux_27_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_27/
mv he_flux_28_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_28/
mv he_flux_29_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_29/
mv he_flux_30_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_30/
mv he_flux_31_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_31/
mv he_flux_32_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_32/
mv he_flux_33_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_33/
mv he_flux_34_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_34/
mv he_flux_35_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_35/
mv he_flux_36_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_36/
mv he_flux_37_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_37/
mv he_flux_38_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_38/
mv he_flux_39_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_39/
mv he_flux_40_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_40/
mv he_flux_41_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_41/
mv he_flux_42_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_42/
mv he_flux_43_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_43/
mv he_flux_44_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_44/
mv he_flux_45_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_45/
mv he_flux_49_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_49/
mv he_flux_50_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_50/
mv he_flux_51_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_51/
mv he_flux_52_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_52/
mv he_flux_53_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_53/
mv he_flux_54_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_54/
mv he_flux_55_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_55/
mv he_flux_56_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_56/
mv he_flux_57_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_57/
mv he_flux_58_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_58/
mv he_flux_59_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_59/
mv he_flux_60_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_60/
mv he_flux_61_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_61/
mv he_flux_62_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_62/
mv he_flux_63_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_63/
mv he_flux_64_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_64/
mv he_flux_65_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_65/
mv he_flux_66_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_66/
mv he_flux_67_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_67/
mv he_flux_68_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_68/
mv he_flux_69_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_69/
mv he_flux_70_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_70/
mv he_flux_71_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_71/
mv he_flux_72_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_72/
mv he_flux_73_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_73/
mv he_flux_74_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_74/
mv he_flux_75_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_75/
mv he_flux_76_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_76/
mv he_flux_77_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_77/
mv he_flux_78_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_78/
mv he_flux_79_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_79/
mv he_flux_80_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_80/
mv he_flux_81_* /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/time_81/
find /afs/cern.ch/work/c/ctuysuz/private/he_flux/root/he_flux_mc_time/ -maxdepth 1 -mindepth 1 -type d -exec sh -c 'echo "{} : $(find "{}" -type f | wc -l)" file\(s\)' \;
